FROM oven/bun:alpine

# Config Bun
ENV PATH="~/.bun/bin:${PATH}"
RUN ln -s /usr/local/bin/bun /usr/local/bin/node

# Update packages
RUN if [ "alpine" == "alpine" ] ; then apk update ; else apt-get update ; fi

COPY . .

RUN bun install

RUN bun install pm2 -g

EXPOSE 3003/tcp

CMD ["pm2-runtime", "start", "--interpreter", "/usr/local/bin/bun", "index.ts"]
