FROM oven/bun:alpine

# Config Bun
ENV PATH="~/.bun/bin:${PATH}"
RUN ln -s /usr/local/bin/bun /usr/local/bin/node

# Update packages
RUN if [ "alpine" == "alpine" ] ; then apk update ; else apt-get update ; fi

COPY . .

RUN bun install

USER bun

EXPOSE 3003/tcp

CMD ["bun", "run" ,"index.ts" ]