import fs from "fs/promises";

const statsObj: any = {
  "2024-09-18": {
    nb_uniq_visitors: 3292,
    nb_visits: 4319,
    nb_users: 0,
    nb_actions: 35376,
    max_actions: 204,
    bounce_count: 1001,
    sum_visit_length: 2240651,
    nb_visits_new: 1102,
    nb_actions_new: 7424,
    nb_uniq_visitors_new: 1102,
    nb_users_new: 0,
    max_actions_new: 123,
    bounce_rate_new: "33%",
    nb_actions_per_visit_new: 6.7,
    avg_time_on_site_new: 369,
    nb_visits_returning: 3217,
    nb_actions_returning: 27952,
    nb_uniq_visitors_returning: 2329,
    nb_users_returning: 0,
    max_actions_returning: 204,
    bounce_rate_returning: "20%",
    nb_actions_per_visit_returning: 8.7,
    avg_time_on_site_returning: 570,
    Referrers_visitorsFromSearchEngines: 47,
    Referrers_visitorsFromSocialNetworks: 7,
    Referrers_visitorsFromDirectEntry: 1002,
    Referrers_visitorsFromWebsites: 3263,
    Referrers_visitorsFromCampaigns: 0,
    Referrers_distinctSearchEngines: 4,
    Referrers_distinctSocialNetworks: 1,
    Referrers_distinctKeywords: 1,
    Referrers_distinctWebsites: 67,
    Referrers_distinctWebsitesUrls: 127,
    Referrers_distinctCampaigns: 0,
    nb_conversions: 0,
    nb_visits_converted: 0,
    revenue: 0,
    conversion_rate: "0%",
    nb_conversions_new_visit: 0,
    nb_visits_converted_new_visit: 0,
    revenue_new_visit: 0,
    conversion_rate_new_visit: "0%",
    nb_conversions_returning_visit: 0,
    nb_visits_converted_returning_visit: 0,
    revenue_returning_visit: 0,
    conversion_rate_returning_visit: "0%",
    nb_pageviews: 34809,
    nb_uniq_pageviews: 20471,
    nb_downloads: 33,
    nb_uniq_downloads: 27,
    nb_outlinks: 534,
    nb_uniq_outlinks: 472,
    nb_searches: 0,
    nb_keywords: 0,
    Referrers_visitorsFromDirectEntry_percent: "1%",
    Referrers_visitorsFromSearchEngines_percent: "0%",
    Referrers_visitorsFromCampaigns_percent: "0%",
    Referrers_visitorsFromSocialNetworks_percent: "0%",
    Referrers_visitorsFromWebsites_percent: "4%",
    bounce_rate: "23%",
    nb_actions_per_visit: 8.2,
    avg_time_on_site: 519,
  },
  "2024-09-19": {
    nb_uniq_visitors: 3303,
    nb_visits: 4405,
    nb_users: 0,
    nb_actions: 35774,
    max_actions: 193,
    bounce_count: 996,
    sum_visit_length: 2265214,
    nb_visits_new: 1109,
    nb_actions_new: 7231,
    nb_uniq_visitors_new: 1109,
    nb_users_new: 0,
    max_actions_new: 71,
    bounce_rate_new: "34%",
    nb_actions_per_visit_new: 6.5,
    avg_time_on_site_new: 383,
    nb_visits_returning: 3296,
    nb_actions_returning: 28543,
    nb_uniq_visitors_returning: 2343,
    nb_users_returning: 0,
    max_actions_returning: 193,
    bounce_rate_returning: "19%",
    nb_actions_per_visit_returning: 8.7,
    avg_time_on_site_returning: 558,
    Referrers_visitorsFromSearchEngines: 37,
    Referrers_visitorsFromSocialNetworks: 4,
    Referrers_visitorsFromDirectEntry: 983,
    Referrers_visitorsFromWebsites: 3381,
    Referrers_visitorsFromCampaigns: 0,
    Referrers_distinctSearchEngines: 4,
    Referrers_distinctSocialNetworks: 3,
    Referrers_distinctKeywords: 1,
    Referrers_distinctWebsites: 72,
    Referrers_distinctWebsitesUrls: 145,
    Referrers_distinctCampaigns: 0,
    nb_conversions: 0,
    nb_visits_converted: 0,
    revenue: 0,
    conversion_rate: "0%",
    nb_conversions_new_visit: 0,
    nb_visits_converted_new_visit: 0,
    revenue_new_visit: 0,
    conversion_rate_new_visit: "0%",
    nb_conversions_returning_visit: 0,
    nb_visits_converted_returning_visit: 0,
    revenue_returning_visit: 0,
    conversion_rate_returning_visit: "0%",
    nb_pageviews: 35182,
    nb_uniq_pageviews: 20917,
    nb_downloads: 53,
    nb_uniq_downloads: 41,
    nb_outlinks: 539,
    nb_uniq_outlinks: 467,
    nb_searches: 0,
    nb_keywords: 0,
    Referrers_visitorsFromDirectEntry_percent: "1%",
    Referrers_visitorsFromSearchEngines_percent: "0%",
    Referrers_visitorsFromCampaigns_percent: "0%",
    Referrers_visitorsFromSocialNetworks_percent: "0%",
    Referrers_visitorsFromWebsites_percent: "4%",
    bounce_rate: "23%",
    nb_actions_per_visit: 8.1,
    avg_time_on_site: 514,
  },
  "2024-09-20": {
    nb_uniq_visitors: 2891,
    nb_visits: 3821,
    nb_users: 0,
    nb_actions: 31339,
    max_actions: 143,
    bounce_count: 794,
    sum_visit_length: 2027302,
    nb_visits_new: 920,
    nb_actions_new: 5844,
    nb_uniq_visitors_new: 920,
    nb_users_new: 0,
    max_actions_new: 64,
    bounce_rate_new: "31%",
    nb_actions_per_visit_new: 6.4,
    avg_time_on_site_new: 404,
    nb_visits_returning: 2901,
    nb_actions_returning: 25495,
    nb_uniq_visitors_returning: 2093,
    nb_users_returning: 0,
    max_actions_returning: 143,
    bounce_rate_returning: "18%",
    nb_actions_per_visit_returning: 8.8,
    avg_time_on_site_returning: 571,
    Referrers_visitorsFromSearchEngines: 31,
    Referrers_visitorsFromSocialNetworks: 4,
    Referrers_visitorsFromDirectEntry: 893,
    Referrers_visitorsFromWebsites: 2893,
    Referrers_visitorsFromCampaigns: 0,
    Referrers_distinctSearchEngines: 5,
    Referrers_distinctSocialNetworks: 1,
    Referrers_distinctKeywords: 1,
    Referrers_distinctWebsites: 67,
    Referrers_distinctWebsitesUrls: 138,
    Referrers_distinctCampaigns: 0,
    nb_conversions: 0,
    nb_visits_converted: 0,
    revenue: 0,
    conversion_rate: "0%",
    nb_conversions_new_visit: 0,
    nb_visits_converted_new_visit: 0,
    revenue_new_visit: 0,
    conversion_rate_new_visit: "0%",
    nb_conversions_returning_visit: 0,
    nb_visits_converted_returning_visit: 0,
    revenue_returning_visit: 0,
    conversion_rate_returning_visit: "0%",
    nb_pageviews: 30820,
    nb_uniq_pageviews: 18298,
    nb_downloads: 25,
    nb_uniq_downloads: 21,
    nb_outlinks: 494,
    nb_uniq_outlinks: 437,
    nb_searches: 0,
    nb_keywords: 0,
    Referrers_visitorsFromDirectEntry_percent: "1%",
    Referrers_visitorsFromSearchEngines_percent: "0%",
    Referrers_visitorsFromCampaigns_percent: "0%",
    Referrers_visitorsFromSocialNetworks_percent: "0%",
    Referrers_visitorsFromWebsites_percent: "3%",
    bounce_rate: "21%",
    nb_actions_per_visit: 8.2,
    avg_time_on_site: 531,
  },
  "2024-09-21": {
    nb_uniq_visitors: 407,
    nb_visits: 485,
    nb_users: 0,
    nb_actions: 3973,
    max_actions: 107,
    bounce_count: 145,
    sum_visit_length: 208967,
    nb_visits_new: 177,
    nb_actions_new: 1267,
    nb_uniq_visitors_new: 177,
    nb_users_new: 0,
    max_actions_new: 77,
    bounce_rate_new: "42%",
    nb_actions_per_visit_new: 7.2,
    avg_time_on_site_new: 256,
    nb_visits_returning: 308,
    nb_actions_returning: 2706,
    nb_uniq_visitors_returning: 247,
    nb_users_returning: 0,
    max_actions_returning: 107,
    bounce_rate_returning: "23%",
    nb_actions_per_visit_returning: 8.8,
    avg_time_on_site_returning: 532,
    Referrers_visitorsFromSearchEngines: 11,
    Referrers_visitorsFromSocialNetworks: 4,
    Referrers_visitorsFromDirectEntry: 116,
    Referrers_visitorsFromWebsites: 354,
    Referrers_visitorsFromCampaigns: 0,
    Referrers_distinctSearchEngines: 3,
    Referrers_distinctSocialNetworks: 3,
    Referrers_distinctKeywords: 1,
    Referrers_distinctWebsites: 18,
    Referrers_distinctWebsitesUrls: 32,
    Referrers_distinctCampaigns: 0,
    nb_conversions: 0,
    nb_visits_converted: 0,
    revenue: 0,
    conversion_rate: "0%",
    nb_conversions_new_visit: 0,
    nb_visits_converted_new_visit: 0,
    revenue_new_visit: 0,
    conversion_rate_new_visit: "0%",
    nb_conversions_returning_visit: 0,
    nb_visits_converted_returning_visit: 0,
    revenue_returning_visit: 0,
    conversion_rate_returning_visit: "0%",
    nb_pageviews: 3898,
    nb_uniq_pageviews: 2234,
    nb_downloads: 13,
    nb_uniq_downloads: 9,
    nb_outlinks: 62,
    nb_uniq_outlinks: 51,
    nb_searches: 0,
    nb_keywords: 0,
    Referrers_visitorsFromDirectEntry_percent: "0%",
    Referrers_visitorsFromSearchEngines_percent: "0%",
    Referrers_visitorsFromCampaigns_percent: "0%",
    Referrers_visitorsFromSocialNetworks_percent: "0%",
    Referrers_visitorsFromWebsites_percent: "0%",
    bounce_rate: "30%",
    nb_actions_per_visit: 8.2,
    avg_time_on_site: 431,
  },
  "2024-09-22": {
    nb_uniq_visitors: 224,
    nb_visits: 251,
    nb_users: 0,
    nb_actions: 1590,
    max_actions: 113,
    bounce_count: 104,
    sum_visit_length: 77372,
    nb_visits_new: 108,
    nb_actions_new: 623,
    nb_uniq_visitors_new: 108,
    nb_users_new: 0,
    max_actions_new: 71,
    bounce_rate_new: "46%",
    nb_actions_per_visit_new: 5.8,
    avg_time_on_site_new: 288,
    nb_visits_returning: 143,
    nb_actions_returning: 967,
    nb_uniq_visitors_returning: 123,
    nb_users_returning: 0,
    max_actions_returning: 113,
    bounce_rate_returning: "38%",
    nb_actions_per_visit_returning: 6.8,
    avg_time_on_site_returning: 324,
    Referrers_visitorsFromSearchEngines: 2,
    Referrers_visitorsFromSocialNetworks: 2,
    Referrers_visitorsFromDirectEntry: 82,
    Referrers_visitorsFromWebsites: 165,
    Referrers_visitorsFromCampaigns: 0,
    Referrers_distinctSearchEngines: 1,
    Referrers_distinctSocialNetworks: 1,
    Referrers_distinctKeywords: 1,
    Referrers_distinctWebsites: 14,
    Referrers_distinctWebsitesUrls: 17,
    Referrers_distinctCampaigns: 0,
    nb_conversions: 0,
    nb_visits_converted: 0,
    revenue: 0,
    conversion_rate: "0%",
    nb_conversions_new_visit: 0,
    nb_visits_converted_new_visit: 0,
    revenue_new_visit: 0,
    conversion_rate_new_visit: "0%",
    nb_conversions_returning_visit: 0,
    nb_visits_converted_returning_visit: 0,
    revenue_returning_visit: 0,
    conversion_rate_returning_visit: "0%",
    nb_pageviews: 1550,
    nb_uniq_pageviews: 931,
    nb_downloads: 1,
    nb_uniq_downloads: 1,
    nb_outlinks: 39,
    nb_uniq_outlinks: 32,
    nb_searches: 0,
    nb_keywords: 0,
    Referrers_visitorsFromDirectEntry_percent: "0%",
    Referrers_visitorsFromSearchEngines_percent: "0%",
    Referrers_visitorsFromCampaigns_percent: "0%",
    Referrers_visitorsFromSocialNetworks_percent: "0%",
    Referrers_visitorsFromWebsites_percent: "0%",
    bounce_rate: "41%",
    nb_actions_per_visit: 6.3,
    avg_time_on_site: 308,
  },
};

async function generic() {
  const series_config = [
    { label: "Visits", prop: "bounce_count" },
    { label: "Bounce Count", prop: "bounce_count" },
    { label: "Total Visits", prop: "sum_visit_length" },
  ];

  const headings = Object.keys(statsObj);
  const series = series_config.map((config: any) => {
    const serieValues = headings.map((key: string) => {
      return statsObj[key][config.prop];
    });
    return [config.label, ...serieValues];
  }, []);

  const data = [["_", ...headings], ...series];

  return data;
}

async function main() {
  const headings = Object.keys(statsObj);
  const visits = headings.map((date: any) => {
    return statsObj[date].nb_visits;
  });
  const uniq_visitors = headings.map((date: any) => {
    return statsObj[date].nb_uniq_visitors;
  });
  const visits_new = headings.map((date: any) => {
    return statsObj[date].nb_visits_new;
  });

  const data = [
    ["_", ...headings],
    ["Visits", ...visits],
    ["Uniq Visitors", ...uniq_visitors],
    ["New Visits", ...visits_new],
  ];

  return data;
}

(async () => {
  let data = {};
  // data = await main();
  data = await generic();
  await fs.writeFile(
    "sample_data.json",
    JSON.stringify(data, null, 2),
    "utf-8"
  );
})();
