{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dataviz-srv.fullname" . }}
  labels:
    {{- include "dataviz-srv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dataviz-srv.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingress.from }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- range .Values.networkPolicy.egress.to }}
    - to:
        - {{- toYaml . | nindent 10 }}
    {{- end }}
  {{- end }}
{{- end }}