replicaCount: 3

image:
  repository: ghcr.io/teamdigitale/dataviz-srv
  tag: main
  pullPolicy: IfNotPresent

env:
  NODE_ENV: production
  LOG_LEVEL: warn

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
  hosts:
    - host: dataviz.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dataviz-prod-tls
      hosts:
        - dataviz.example.com

# Use external managed database in production
postgresql:
  enabled: false

externalDatabase:
  host: postgres.example.com
  port: 5432
  username: dataviz
  database: dataviz_prod
  existingSecret: dataviz-db-secret
  existingSecretPasswordKey: password

secrets:
  existingSecret: dataviz-secrets

serviceMonitor:
  enabled: true
  namespace: monitoring

networkPolicy:
  enabled: true
  ingress:
    enabled: true
    from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
  egress:
    enabled: true
    to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector: {}
      namespaceSelector:
        matchLabels:
          name: cert-manager
