name: pull-request

on:
  push:
    branches:
      - "**"
    # branches: [main]
  pull_request:
    branches: [main]
    # for future develpments
    # tags:
    #   - v*

permissions:
  # To push Docker images to GitHub
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/teamdigitale/dataviz-srv:
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "Dockerfile.app"
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          # tags: |
          #   ghcr.io/teamdigitale/dataviz-srv:latest
          #   ghcr.io/teamdigitale/dataviz-srv:0.0.1
